# Site Settings
name: VerMangaHentai
title: VerMangaHentai | Gratis Hentai Manga, Doujinshi y Anime XXX
description: Bienvenidos a nuestro sitio manga hentai en línea, donde puedes disfrutar de tus mangas eroticos favoritos sin límites y de forma gratuita. Ofrecemos una amplia selección de títulos de manga hentai de diferentes géneros y autores, actualizados regularmente para que siempre tengas algo nuevo y emocionante que leer. Nuestro catálogo está disponible las 24 horas del día, los 7 días de la semana, para que puedas leer manga en línea cuando y donde quieras. Además, nuestra página está optimizada para SEO con palabras clave como "leer manga hentai gratis en línea", "catálogo manga gratuito en línea", "sin descargas manga", etc. Ofrecemos una experiencia de lectura agradable y sin interrupciones, así como un diseño atractivo y fácil de usar. ¡Comienza tu aventura manga hoy y disfruta de la mejor experiencia de lectura manga en línea gratis!
tags:
  - blog
  - manga
  - hentai
  - manga hentai
  - manga porno
  - Anime porno
  - manga porno español
  - manga hentai español
  - Anime XXX
show_hero: true
menu:
  - title: Home
    url: /
  - tittle: RedesSociales
    url: /redessociales
  - title: About
    url: /about
  - title: Categorias
    url: /tags
  - title: Contacto
    url: /contact
  - title: Feed
    url: /feed.xml
email: hackyeshua12@gmail.com
# See: https://disqus.com/
disqus_username: pak_guitar
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xlevvqzq


# Social Media Settings
# Remove the item if you don't need it
# github_username: github_username
# facebook_username: facebook_username
twitter_username: vermangahentai
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "349424108"
language: "es"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
#version: v3.1.2
